services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./volumes/telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    command: >
      --api-id=${TELEGRAM_API_ID}
      --api-hash=${TELEGRAM_API_HASH}
      --local
      --dir=/var/lib/telegram-bot-api
      --http-port=8081
      --log=/var/lib/telegram-bot-api/telegram-bot-api.log

  nginx:
    image: nginx:1.29.0-alpine
    restart: unless-stopped
    depends_on:
      - telegram-bot-api
    volumes:
      - ./volumes/telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8082:80"