services:
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    environment:
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
    command: >
      --api-id=${TELEGRAM_API_ID}
      --api-hash=${TELEGRAM_API_HASH}
      --local
      --dir=/var/lib/telegram-bot-api
      --http-port=8081
      --log=/var/lib/telegram-bot-api/telegram-bot-api.log
#    networks:
#      - bot-network

volumes:
  telegram-bot-api-data:
    driver: local

#networks:
#  bot-network:
#    external: true
#    name: tg-translation-bot_default