services:
  # https://github.com/aiogram/telegram-bot-api/blob/master/docker-entrypoint.sh#L100
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    volumes:
      - "./volumes/telegram-bot-api-data:/var/lib/telegram-bot-api"
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_LOCAL: 1
      TELEGRAM_WORK_DIR: /var/lib/telegram-bot-api
      TELEGRAM_HTTP_PORT: 8081
      TELEGRAM_LOG_FILE: /var/lib/telegram-bot-api/telegram-bot-api.log
    ports:
      - "8081:8081"

  nginx:
    image: nginx:1.29.0-alpine
    restart: unless-stopped
    depends_on:
      - telegram-bot-api
    volumes:
      - "./volumes/telegram-bot-api-data:/var/lib/telegram-bot-api"
      - "./nginx:/etc/nginx/conf.d/"
    ports:
      - "8082:80"