services:
  telegram-dify-bot:
    image: ghcr.io/qin2dim/telegram-dify-bot:latest
    restart: always
    container_name: telegram-dify-bot
    env_file:
      - .env
    volumes:
      - "./logs:/app/app/logs"
    command: uv run app/main.py
